### ISSUE TITLE
Text size too small

### ISSUE THREAD

**Issue by t0str** [abe33/atom-tablr#10]
Having a HiDPI screen, I can barely read the text in the table-view (i.e. the cells). If I double click a cell, I get my usual font in the usual size an all is fine. Presumably there is a way to set this in styles.less, but I was not able to find which class I had to adapt (I'm not really a css guy).

A setting for Font & Size would be very nice, but if you can tell me which css class I have to set, that would be rad too!

Otherwise this addon is amazing, I don't know why I didn't go looking for something like this earlier. Thank you very much for your work, it's much appreciated!

**Comment by abe33** [comment]
Thanks for the report, I didn't thought much about these use case until now but I'll definitely try to provide a solution for that too. Would you mind sharing a screenshot of what you get so that I can an idea of the problem while I think to a solution?

**Comment by t0str** [comment]
Sure, here you go.

* This is your table-view:
![atom_1](https://cloud.githubusercontent.com/assets/231959/10214501/13931590-6819-11e5-877d-7c45cb847121.png)

* This is the same file in plain text (size difference)
![atom_2](https://cloud.githubusercontent.com/assets/231959/10214503/1de9087e-6819-11e5-8a99-5517609f919c.png)

* This is the dialog to choose table/text editor, here the fontsize seems good, but the window is rather small
![atom_3](https://cloud.githubusercontent.com/assets/231959/10214504/2171aa14-6819-11e5-9ac9-8b8b6a1a97eb.png)


Software:
* Atom 1.0.19
* Fedora 22 (4.1.7-200.fc22.x86_64)
* tablr 0.2.2

If you need anything else just let me know.

**Comment by abe33** [comment]
@t0str thank you for that :bow:, one last question, can you tell me what `devicePixelRatio` value is reported in Atom?

As far as I can tell there's two issues here, the font-size which is too small, but also the column width and row heigh settings that are not scaled properly. I'll take a look at both issues soon.

**Comment by t0str** [comment]
@abe33 Assuming this is the correct way of obtaining the value: 1
(I opened Debugger Tools and entered console.log(devicePixelRatio))

**Comment by abe33** [comment]
Yes, that's the way, thanks. I think I have enough information now, I'll update as soon as I have a solution for that.

**Comment by abe33** [comment]
@t0str I just published a version where all the font-size use ems instead of pixels. It should fix the font scale issue. Let me know if things improved for you.

As for the columns width and row height, I suggest you tweak the corresponding tablr settings to better fit your screen. I'll search for a better solution.

**Comment by t0str** [comment]
Thanks for your quick support! That's a massive improvement, I can set up the table to be readable. 
![atom_5](https://cloud.githubusercontent.com/assets/231959/10221218/6ae0e924-684d-11e5-9622-de6646f70851.png)

However the tablr-dialog does suffer some damage :)
![atom_4](https://cloud.githubusercontent.com/assets/231959/10221236/7bd9e67c-684d-11e5-82f5-e130805412ed.png)

From looking at it, the preview table seems to do everything right. Width, text size etc. Maybe this helps.

**Comment by abe33** [comment]
Oh right!, nice catch, actually I tried to improve the layout for larger screen, but removed a width limitation on the preview table, but I should have not. I'll fix that right away.

**Comment by abe33** [comment]
@t0str v0.2.4 should be better now :)

**Comment by t0str** [comment]
@abe33 Thanks, looking good!

So the major problems are solved, and the width/height I can adjust manually. I even found the way to set my font in styles.less:
```
// font for tablr table
atom-table-editor::shadow atom-table-cell {
  font-family: "Envy Code R";
}
```

So thank you very much, this was amazing support!
