### ISSUE TITLE
Support other file extensions

### ISSUE THREAD

**Issue by adrean** [abe33/atom-tablr#11]
That'd be great to support other file extensions (.tsv for example). Even greater if the user could specify the list of file extensions he wants in settings.
My workaround was to change the `return unless /\.csv$/.test uriToOpen` line in `lib/tablr.coffee` but this is overriden on updates.

Anyway, awesome work, I've been looking for a table editor for a while, yours is great!

**Comment by abe33** [comment]
Hi @adrean, thanks for the suggestion and the kind words, I'll add a setting for that with `csv` and `tsv` as default values. Do you know if there's other common extensions besides these two?

**Comment by adrean** [comment]
Awesome, thanks!
I think `tsv` and `csv` are the more common file extensions for delimited data files :smile:
