### ISSUE TITLE
bogus display with more than 100 columns 

### ISSUE THREAD

**Issue by Samuel29** [abe33/atom-tablr#12]
Hi . Generate a tsv with 150 columns, with ie. this shell command:
```
    for i in `seq -w 000 150`; do echo -ne "$i\t"; done > tablr_column_bug.tsv
```
then open it with Atom: in the tablr wizard, choose "\t" as field separator then "open table editor"
scroll horizontally to the right.
At some point rendering becomes bogus, we don't see columns anymore, clicking on other columns doesn't seem to be working... scrolling with arrow keys seems to work, but nothing appears.
see the attached animated gif capture here:
![atom-tablr-columns-bug](https://cloud.githubusercontent.com/assets/1901769/10633925/7bb46856-77ee-11e5-8bea-1027e624237b.gif)

**Comment by abe33** [comment]
Hi @Samuel29, nice catch, seems like at some point the last visible column can no longer can be computed properly.
