### ISSUE TITLE
Could I change encoding ?

### ISSUE THREAD

**Issue by sekitaka** [abe33/atom-tablr#22]
Hello, 
Thanks for your amazing product.

I have a question.
Can I change encoding on tablr? 
I'd like to use ShiftJIS.

thank you.

**Comment by abe33** [comment]
Hi @sekitaka, thanks for the suggestion! 

I haven't really thought about it at first, but it looks like a must have feature. I'll try to find some time for work on this.

**Comment by abe33** [comment]
I have implemented a first version in 0.10, let me know if you see any improvement to make.

**Comment by sekitaka** [comment]
Hello @abe33.
Thank you a lot! 
I have used new version, and I can edit ShiftJIS files. 

Thanks again;)
