### ISSUE TITLE
Change column ordering

### ISSUE THREAD

**Issue by p0la** [abe33/atom-tablr#24]
Hi 

Thanks again for the work. It's very useful. 

A new feature that would be great would be the ability to modify column or line position. 

Maybe I missed it but I couldn't find a way to invert column 2 and 3 for example. 

I guess the best interface would be something a la Excel where you can Drag and Drop column header (will conflict with ordering though). It also what stuff like ExtJs does: http://dev.sencha.com/extjs/5.1.0/examples/grid/row-editing.html
An other solution (I think quite common as well) would  be to have move left, move right buttons in the column header. 

That would be very handy !

**Comment by abe33** [comment]
Hmm, you're right, I've missed that, I'll add it to my TODO. Thanks for the suggestion.
