### ISSUE TITLE
insert / delete column

### ISSUE THREAD

**Issue by p0la** [abe33/atom-tablr#25]
Would be very useful. 

Most tableur uses "Ctrl -" as shortcut to delete selected row or selected column. 

If you decide to do this, supper useful standard shortcut would also be: 
"Shift Space": Select row
"Ctrl Space": Select column

I'm under the impression that those a re quite standard (Excel pushing the standard ?). Not sure about mac conventions though..

**Comment by p0la** [comment]
ok, my bad. Found it in your cheat sheet.

Short cut don't seem to work for me but I can certainly live with the command. 

Thanks

**Comment by abe33** [comment]
> Short cut don't seem to work for me but I can certainly live with the command. 

You can still change the keybinding if you find something more convenient. 
The principle is the same than for splitting panes, meaning you first press <kbd>cmd-shift-n</kbd> (or <kbd>ctrl-shift-n</kbd> for win/linux) then you release and press a direction. Same thing for deletion with a different base shortcut.
