### ISSUE TITLE
Display only first N elments on table preview

### ISSUE THREAD

**Issue by lokifacio** [abe33/atom-tablr#26]
I think it would be very useful, specially for big files, to display only some rows of the table in order to configure or decide if you really want to load the whole file.

Do you think this is possible or you already get the file buffered when your plugin is invoked?

Great work anyway.

**Comment by abe33** [comment]
I was doing that in the first versions, but I dropped it at some point given that it was leading to more errors than I thought it would. For instance, if you have an escaped character after the last preview line you won't see any issue in the preview, but you won't be able to open the file as you'll have to specify the proper escape character. 

I could probably reintroduce it behind a setting as you suggested.

**Comment by lokifacio** [comment]
If that happens you won't be able to open it anyway. I think it would be clearer if you just display an error message and revert to normal mode in that case .

Adding an option is a good compromise anyway.

**Comment by abe33** [comment]
So, I started looking at how I could do it again, but i face a serious issue for the moment. I'm now supporting the whole list of encoding supported by a text editor, but that implied to use the Atom's `File` object. But that object doesn't provide any means to get a read stream of the file. So if I want to show only the 5 first rows I'll still have to read and parse the whole file (with a stream I could it when reaching the specified amount). So I'll have to wait that a stream API get available to implement properly this feature.
