### ISSUE TITLE
Ignores cells after #

### ISSUE THREAD

**Issue by pi3rre** [abe33/atom-tablr#27]
I think it considers the rest of the line as comment, even though it is a valid entry for my table, eg:
A,#1,3
2,B,4
Is '#' considered special character in csv files?
Thanks for this package anyway!

**Comment by abe33** [comment]
> Is '#' considered special character in csv files?

That's the default, yes, but you can change it using the corresponding field in the opening form: 

![sample_csv_-_spec_fixtures_ __users_cedric_github_tablr](https://cloud.githubusercontent.com/assets/247140/12340862/d05abb36-bb1d-11e5-8244-f188419d71aa.png)

If you just want to disable it, select `custom` and leave the input field empty. I think it'll deserve a specific option in the button group and I'll add one in the next release.

**Comment by pi3rre** [comment]
Ok, thanks. But how do I get to see the opening form again if already chose the table format and saved the choice for future openings?

**Comment by abe33** [comment]
Right, I haven't implemented anything for this specific use case (clearing the choice of opening in a table or a text editor). 
You can still use the `Tablr: Clear csv storage` command. It'll get rid of everything that was stored for csv files (even the config for each file, so you'll have to make the setup again).

**Comment by abe33** [comment]
I added two more commands to clear the choices and the layouts separetely. I think I can close this issue then.

**Comment by jan-glx** [comment]
What are the commands? Could you add them to the documentation, please? (See #66 )
