### ISSUE TITLE
Is it already released?

### ISSUE THREAD

**Issue by rugk** [abe33/atom-tablr#4]
Just asking this because I can't find it:
![tableedit](https://cloud.githubusercontent.com/assets/11966684/9529252/8e027f9a-4cf9-11e5-9468-8245fa1288a7.PNG)

**Comment by abe33** [comment]
Nope, I still haven't published it yet. 
It gets closer and closer to the point I can release it, but I lacked time to make sure things are polished enough before making it available publicly. 
I plan to use the next week to work on my various packages and this one is part of the TODO.

**Comment by abe33** [comment]
Now it is :)
