### ISSUE TITLE
Settings panel shows up for *.coffee file

### ISSUE THREAD

**Issue by jneuendorf** [abe33/atom-tablr#45]
Hi,

I have a file named "CSVExporter.coffee". When I open it from the tree view the settings panel opens up and asks which editor to use (table or text).
Choosing the text editor and editing the file works normally but I didn't want to get asked in the first place.
Maybe this is related to the file name that contains "csv"?
I couldn't find anything that causes the problem quickly so I hope you can fix it :)

**Comment by jneuendorf** [comment]
Thank you! :)

**Comment by abe33** [comment]
No pb :), I forgot to update the issue after releasing the patch
