### ISSUE TITLE
First preview of the parsed CSV has an error when default Header property is activated

### ISSUE THREAD

**Issue by ruget** [abe33/atom-tablr#49]
In Tblr setting, change de fault header property:
![image](https://cloud.githubusercontent.com/assets/11539705/14941111/b455d05c-0f90-11e6-8dd1-cec93cea963c.png)

> I've also setted ';' as default separator

Next, open a new csv file. You'll see the **Header** property selected as expected.
But I get an error in the **Preview of the parsed CSV**
![image](https://cloud.githubusercontent.com/assets/11539705/14941098/4ddf58c0-0f90-11e6-80b7-778fa70164e9.png)

Unselect the **Header** property and, the preview is displayed.
![image](https://cloud.githubusercontent.com/assets/11539705/14941105/7f17a35c-0f90-11e6-8433-71df7451bd52.png)

Next, you can select the **Header** property again and **Open Table Editor** activated.
![image](https://cloud.githubusercontent.com/assets/11539705/14941129/71b30a3e-0f91-11e6-8ed9-92ddf2107db7.png)

Atom 1.7.2
Tablr 1.2.3
Mac OS X

Thanks

**Comment by abe33** [comment]
Hi @ruget, thanks for the detailed explanation, would you mind sharing a sample file with me? I would like to be sure I have the same data to reproduce the issue.

**Comment by ruget** [comment]
Hi @abe33, 

Here the file:
[LeakageRatioByReaderV1.csv.zip](https://github.com/abe33/atom-tablr/files/246361/LeakageRatioByReaderV1.csv.zip)

Thanks for tablr, this is a nice tool and I use it to have a quick overview of csv files 👍
