### ISSUE TITLE
No cross cursor on scrollbars

### ISSUE THREAD

**Issue by rugk** [abe33/atom-tablr#5]
On the scrollbars there should not be displayed the cross cursor, but just the normal one:
![scrollbarcursor](https://cloud.githubusercontent.com/assets/11966684/10117060/c5444e9a-6449-11e5-9709-60fb6f6ae970.png)

**Comment by abe33** [comment]
Oh,right, I'll see how I can fix that, thanks for the report.

**Comment by abe33** [comment]
Actually it seems the `cursor` property isn't honored on `:webkit-scrollbar` and derived selector. I'm not sure how to fix this but I'll try a few things before giving up.

**Comment by rugk** [comment]
> but I'll try a few things before giving up.

That's always a good idea... :wink:

**Comment by abe33** [comment]
Haha, it appears it was much more simple that I thought at first, as I already had a wrapper between the scroll container and the cells I just moved the `cursor: cell` one level deeper.
