### ISSUE TITLE
Failed to load the tablr package

### ISSUE THREAD

**Issue by esjay** [abe33/atom-tablr#50]
1. Choose the [Seti UI theme](https://atom.io/themes/seti-ui)
2. Receive stack trace error.

**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.4
**Thrown From**: [tablr](https://github.com/abe33/atom-tablr) package, v1.2.3

### Stack Trace

Failed to load the tablr package

```
At .btn is undefined in /Users/wayne/.atom/packages/tablr/styles/tablr.less:896:12

LessError: .btn is undefined
  at /Users/wayne/.atom/packages/tablr/styles/tablr.less:896:12
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-flake8",
      "node-resolver",
      "linter-jshint",
      "js-autoimport"
    ],
    "themes": [
      "seti-ui",
      "an-old-hope-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
an-old-hope-syntax, v0.5.0
angularjs, v0.3.4
atom-django, v0.3.2
atom-handlebars, v1.3.0
atom-ternjs, v0.14.1
atom-typescript, v8.9.1
auto-run, v0.2.1
autocomplete-modules, v1.4.1
browser-plus, v0.0.60
color-picker, v2.1.1
editorconfig, v1.4.1
hyperclick, v0.0.36
js-hyperclick, v1.4.2
language-diff, v0.4.0
language-javascript-jsx, v0.3.7
language-python-django-templates, v0.1.0
linter, v1.11.4
linter-doiuse, v0.2.3
linter-eslint, v7.2.1
linter-js-yaml, v1.2.5
linter-jsonlint, v1.2.5
linter-less, v2.5.0
linter-tidy, v2.1.0
minimap, v4.23.2
minimap-autohide, v0.10.1
minimap-bookmarks, v0.3.0
minimap-find-and-replace, v4.5.1
minimap-git-diff, v4.3.0
minimap-pigments, v0.2.0
pigments, v0.26.0
pretty-json, v1.0.3
project-manager, v2.9.7
seti-ui, v1.0.3
sync-settings, v0.7.2
tablr, v1.2.3
tabs-to-spaces, v1.0.2
tool-bar, v0.4.0
webbox-color, v0.5.9

# Dev
No dev packages
```

**Comment by esjay** [comment]
Updated issue to note that [Seti UI theme](https://atom.io/themes/seti-ui) seems to be a necessary step in recreating this specific issue.

**Comment by abe33** [comment]
Hi @esjay,

Yep, it looks like the Seti UI theme only define `button.btn` instead of just `.btn` which make the tablr unable to extend the button styles. I'll see if I can find a way around that, and open a ticket on Seti UI Theme to see if we can find a better solution.

**Comment by abe33** [comment]
Since my PR on Seti UI was merged and published, I'll be closing that issue, feel free to open a new issue if you find another problem with a theme.
