### ISSUE TITLE
Table view does not reflect changes

### ISSUE THREAD

**Issue by NickyHeuperman** [abe33/atom-tablr#51]
When I edit a cell and confirm the change by pressing Enter the file is actually changed on save but has to be reloaded to reflect the change

**Comment by NickyHeuperman** [comment]
This seems to fix itself when moving to another row

**Comment by abe33** [comment]
That's not the expected behaviour, and it looks a lot like#42 to me. I'm still unable to reproduce that locally so any information is useful at the time.
