### ISSUE TITLE
Changes to new and/or empty files aren't saved

### ISSUE THREAD

**Issue by rafaskb** [abe33/atom-tablr#58]
Steps to reproduce the bug:

1. From Atom's Tree View, create a new file called test.csv.
2. Open it with Tablr's Table Editor.
3. Create a few rows and columns.
4. Save the file by hitting Cmd+S (or Ctrl+S).
5. Close the file.
6. Open the file (either with Table Editor or Text Editor). The file will be empty.

It seems that you need to make some changes in the text editor, like adding an empty column or row before the Table Editor is able to save the changes.

**Comment by abe33** [comment]
Hi @rafaskb, thank you for reporting this, I'll have some time this week end to fix this.
