### ISSUE TITLE
Text field bounds exceed screen limits

### ISSUE THREAD

**Issue by rafaskb** [abe33/atom-tablr#59]
When editing a cell to the right of the editor that has a lot of text, the text field exceeds the screen size, making it impossible to read its content.

![Screenshot](https://cloud.githubusercontent.com/assets/2331058/16498818/f2d3bdae-3ed3-11e6-9f79-a3aa0b45ae18.png)

Even if I enable the "Scroll Past End" option, the bug happens.

![Screenshot 2](https://cloud.githubusercontent.com/assets/2331058/16499028/e6f740c2-3ed4-11e6-892f-fa59e9d62a1a.png)

**Comment by abe33** [comment]
Interesting case, it shouldn't be hard to clamp the editor's width to make sure it fits into the window.
