### ISSUE TITLE
The overlap for too long text should not be transparent

### ISSUE THREAD

**Issue by rugk** [abe33/atom-tablr#6]
![toolongtext](https://cloud.githubusercontent.com/assets/11966684/10117070/23a0b10e-644a-11e5-8b39-2e9b10cf31ce.png)

I think it's not that nice that you see the text at the background too, so you cannot easily read the text you actually want to see.
I think the 'overlap box' there should not be transparent.

**Comment by abe33** [comment]
Hi @rugk, thanks for the report.

I'm not sure about the cause as that's not the behavior I get on my computer (see below). Could you inspect the text editor when editing to see if there's a `height` style that apply to it. In my code I only use `min-width` and `min-height` to let the mini editor expand, but maybe there's some pollution from the theme you use (with one-dark and one-light I know it works but I didn't tests much other themes).

![tablr-edit-multiline](https://cloud.githubusercontent.com/assets/247140/10141480/0fbff004-660d-11e5-9524-ca0e503a3dde.gif)

**Comment by rugk** [comment]
Theme: UI: Atom Dark, Syntax: One Dark
System: Windows 7, Atom 1.0.19

![tablr 16](https://cloud.githubusercontent.com/assets/11966684/10142230/ad49acee-6611-11e5-8121-f6aef92496e3.PNG)
(the bar at the bottom is from [editor-stats](https://atom.io/packages/editor-stats))
