### ISSUE TITLE
Recognize CSV files not using *.csv extension

### ISSUE THREAD

**Issue by obeid** [abe33/atom-tablr#61]
CSV files within a GTFS feed use the *.txt extension, I'm sure similar other scenarios exist. It would be beneficial to regonize files based on their content not extension.

Great extension otherwise 👍

**Comment by abe33** [comment]
Hi @obeid, You might want to add these extensions in the `supportedCsvExtensions` setting of the tablr package. It'll make tablr opens these files as CSV.
