### ISSUE TITLE
Tab does not get persistent automatically

### ISSUE THREAD

**Issue by Yajo** [abe33/atom-tablr#65]
You know this [Atom's pending pane items](http://blog.atom.io/2016/03/17/atom-1-6-and-1-7-beta.html) thingy. Well... after editing in a tablr tab, it still is kept as pending, and if you open a different file, it replaces it.

It should get pinned as normal behavior for normal tabs.

Workaround: double-click on the tab.

**Comment by abe33** [comment]
@Yajo thanks for the report, I may have missed something important regarding pending pane items. I'll take a look at that.

**Comment by Yajo** [comment]
With last update, tab is kept when you press "Open with table editor", not when you edit something inside.

**Comment by abe33** [comment]
You mean editing a setting in the CSV opening form? As is, as nothing is saved until you pick a choice in this form I though it made more sense to terminate the pending state when making a choice, but yeah I can also terminate the pending state once the user changed something in the form.

**Comment by Yajo** [comment]
I mean inside the csv itself. Atom works that way: pending until you write anything in the tab. Sometimes I just open a csv to see its contents, and expect it to be non-persistent because I did not edit it. But to see its contents, I press the "Open with table editor" button.

**Comment by abe33** [comment]
Oh, right! I see, let's do that then, that's ok for me.
