### ISSUE TITLE
Looks ugly with atom-material-ui

### ISSUE THREAD

**Issue by Yajo** [abe33/atom-tablr#74]
Not sure if this is a bug on https://github.com/abe33/atom-tablr or on https://github.com/atom-material/atom-material-ui, but when using Atom Material theme + One Dark for colours, see how it looks editing a cell:

![captura de pantalla de 2016-11-11 09-44-21](https://cloud.githubusercontent.com/assets/973709/20209259/b37b1114-a7f3-11e6-9e30-2415fbf27ee0.png)

**Comment by abe33** [comment]
Hi @Yajo, thanks for the report. It looks like Atom Material isn't defining a background to text editor. I can fix that on my end.
