### ISSUE TITLE
Deleting multiple rows/columns 

### ISSUE THREAD

**Issue by HamsterHuey** [abe33/atom-tablr#77]
Thanks for a great extension. Perhaps this is already implemented and I can't seem to figure it out, but at the moment, it seems that I cannot select multiple rows/columns and then use `Ctrl+Alt+Backspace left` to delete all the selected rows/columns. It will still only delete a single row or column, which can make bulk deletion of rows/columns very tedious.

It would be great to implement this if possible (if it isn't already implemented).

**Comment by abe33** [comment]
Nah, you're right, I forgot to implement multiple lines/columns removal. I'll take a look at that. 

Thanks for the report!

**Comment by HamsterHuey** [comment]
That's awesome! Thanks a ton for implementing this!
