### ISSUE TITLE
Tab is not seamless

### ISSUE THREAD

**Issue by simurai** [abe33/atom-tablr#8]
Not a major issue, but when using One dark with a light theme, the tab is not seamless:

![screen shot 2015-09-30 at 11 17 26 am](https://cloud.githubusercontent.com/assets/378023/10182900/f85a915e-6764-11e5-929d-b6cda2809d31.png)

The problem is that if the `type` includes the word "Editor", the One themes will use the `@syntax-background-color` as the tab color. So that the tab looks seamless with the editor. See  https://github.com/atom/tabs/pull/118 and https://github.com/atom/one-dark-ui/pull/76

And since Tablr uses `CSVEditor`, the One themes assume that it uses the background color of the syntax theme. Which isn't the case here.

#### Solution

1. Use `syntax-variables.less` instead. Probably not a small task. Plus then buttons and other controls are not available.
2. Change [CSVEditor](https://github.com/abe33/atom-tablr/search?utf8=%E2%9C%93&q=CSVEditor) to something that doesn't include the word "Editor". Probably also not a small task.

I know, "don't call it xxxEditor" sounds a bit stupid as a convention. An easy short-term solution would be if the One themes add an exception for the Tablr package [here](https://github.com/atom/one-dark-ui/blob/master/styles/tabs.less#L253). Something like `&[data-type$="Editor"]:not([data-type="CSVEditor"]),`. But that can get messy over time.

Maybe this issue needs to be revisited in Core + themes. Somehow packages need a way to the the tab what background color the package is using. But it can't just inline the styles since not all themes like to have seamless tabs.

/cc @jessegrosjean

**Comment by abe33** [comment]
I've started working on this in this branch: https://github.com/abe33/atom-tablr/tree/cn-style-table-using-syntax

The table view works well, minus the contrast between the gutter/header and the cells that is no longer present (there isn't many background colors as with the ui themes). 

Now the thing is that the form part before the table editor still doesn't adapt to the tab background (actually it's a bit of a trick, the CSVEditor composes the table editor in its element when the user choose to open the table editor).

I'll try to changes the background and text color while keeping the buttons as is.

**Comment by abe33** [comment]
This is what I get now, looks legible enough to me, what do you think?

![banners_and_alerts_et_sample_csv_-__users_c_nehemie_github_tablr_-_atom](https://cloud.githubusercontent.com/assets/247140/10196776/dfae7172-6794-11e5-8456-5d96cb16e49e.png)

**Comment by simurai** [comment]
Ya, I think it's fine. Probably not that many people use a dark/light combo.

**Comment by abe33** [comment]
I just published a patch with these changes, I'll close the issue now. Anyway, thanks for the feedback and suggestions :).
