### ISSUE TITLE
Opening multiple csv files hangs when switching to second csv file

### ISSUE THREAD

**Issue by rolfkleef** [abe33/atom-tablr#86]
I have a folder with two csv files. When I start `atom *` in that folder, I get to choose either table or text view for one of the files, but as soon as I switch to the second file Atom hangs: I see the dialog to choose, but Atom is non-responsive.

I can edit the first file, and I can close it: at that point Atom hangs as well. I can open and close other non-csv files, it's just when I switch to another tablr tab when Atom hangs.

I get the message:

     $ /usr/bin/atom: line 130: 26540 Segmentation fault      (core dumped) nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1
    Failed to get crash dump id.
    Report Id: 

The line number varies: 26540, 26726, 26927, 27153, 27911... Atom 1.15.0 x64 on Ubuntu, tablr 1.8.1

test1.csv:

    A,B,C,D
    1,2,3,4
    5,6,7,8

test2.csv:

    X,Y,Z
    9,8,7
    6,5,4

**Comment by abe33** [comment]
Hi @rolfkleef, sorry for the late reply. 

I can confirm the issue, will try to find the root cause.

**Comment by rolfkleef** [comment]
:+1: merci!
