### ISSUE TITLE
Button labels can be hard to read

### ISSUE THREAD

**Issue by simurai** [abe33/atom-tablr#9]
When using:

- UI theme: One Dark
- Syntax theme: Solarized Light

the labels of the selected buttons are hard to read (white on yellow):

![screen shot 2015-09-30 at 12 15 46 pm](https://cloud.githubusercontent.com/assets/378023/10183648/0dcc3c56-676d-11e5-9e7e-b39f755aa8fd.png)

The `@button-background-color-selected` + `@text-color-selected` combo [here](https://github.com/abe33/atom-tablr/blob/master/styles/tablr.less#L778-L779) doesn't seem to match for all themes.

#### Solution

Ideally, there should be a `@button-text-color-selected`. Or core/themes should support "button groups" made with `radio` inputs.

Hmm.. maybe you could try to use Less's `contrast` function:

```less
color: contrast(@button-background-color-selected, white, darken(@text-color-selected,80%));
```

**Comment by abe33** [comment]
I tried the `contrast` tricks, it looks like it could work, I'll make more testing with different ui themes to make sure.
